### ISSUE TITLE
cannot access the link for downloading dataset

### ISSUE THREAD

**Issue by lycutter** [aioz-ai/ICCV19_VQA-CTI#18]
hello, I cannot get access to the link of [provided data ](https://vision.aioz.io/d/965325537ca642a3a822/) to download the dataset. Does this link work well? Thanks!

**Comment by Gazeal** [comment]
Our storage is currently under maintenance due to some unexpected errors. We will inform you later when we have finished the process. Sorry for the inconvenience.

**Comment by lycutter** [comment]
ok, thanks!

**Comment by Gazeal** [comment]
We have finished the maintenance. The data can be downloaded now.

**Comment by lycutter** [comment]
Thanks for your help!
