### ISSUE TITLE
The teacher model training code

### ISSUE THREAD

**Issue by haoopan** [aioz-ai/ICCV19_VQA-CTI#2]
It's a great job.But when I look at the code,it doesn't contain teacher model training net,only provided "teacher_logits". So could you please share the teacher model training code? thank you very much!

**Comment by huytran127** [comment]
I have already updated the training code for the teacher model (cti model for FFOE task). You can get the teacher model  by following:
python src/FFOE/main.py --model cti --gamma 2 --batch_size 256 --output saved_models/VQA2.0/cti
