### ISSUE TITLE
No file called 'data_vqa/train_teacher_logits.pkl'

### ISSUE THREAD

**Issue by Ackesnal** [aioz-ai/ICCV19_VQA-CTI#4]
When I attempted to run your project following the instructions, an error occurred saying:

```
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    question_len=args.question_len)
  File "/OSM/CBR/D61_RCV/students/xu078/ICCV19_VQA-CTI/src/FFOE/dataset.py", line 266, in __init__
    self.teacher_logits = cPickle.load(open(teacher_logits_path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'data_vqa/train_teacher_logits.pkl'

```

And I cannot find this file at [here](https://vision.aioz.io/d/965325537ca642a3a822/?p=/&mode=list) either. Hence, how can I solve it?

**Comment by huytran127** [comment]
You can download the teacher logit for VQA-2.0 and TDIUC dataset at [here](https://vision.aioz.io/d/9951e206d5ae4c4a97a1/)

**Comment by Ackesnal** [comment]
Thank you very much! That link works!
