### ISSUE TITLE
Dimension issue for data_TDIUC train.hdf5 and val.hdf5 features file

### ISSUE THREAD

**Issue by ak-kat** [aioz-ai/ICCV19_VQA-CTI#6]
Hi,
For TDIUC dataset train and val dimension of 'image_features' is: [3339639,2048], [1675180,2048], though total number of images is - 122429. and 57565 respectively.
Please help me to understand the dimension of train.hdf5 and val.hdf5 [here](https://vision.aioz.io/d/965325537ca642a3a822/?p=/data_TDIUC&mode=list), I will be thankful to you.

**Comment by huytran127** [comment]
Hi ak-kat,
The first dimension of 'image_features' is the total number of detected bounding boxes (35 bounding boxes for each image in the average), it is not the total number of the image.

**Comment by ak-kat** [comment]
Thanks @huytran127 for your reply. 3339639 implies ~27 BB.
122429 x 35 = 4285015. I earlier thought you would have considered 36 BB, but still.
Expected dimension -: [122429,35,2048], if I am not wrong.

**Comment by huytran127** [comment]
If I set the number of bounding boxes in faster-RCNN is fixed 35 boxes, the expected dimension will be [122429,35,2048]. However, the number of bounding boxes I set in faster-RCNN is dynamic.
