### ISSUE TITLE
About the image features in the paper

### ISSUE THREAD

**Issue by wanng-ide** [aioz-ai/ICCV19_VQA-CTI#9]
In the paper, you explained that the features of the image on the v7w dataset are grid features and Bottom-up features. So, are grid features used on other data sets? What image features are used in FFOE?
Sorry to disturb you.

**Comment by Gazeal** [comment]
- In Multiple choice VQA(MC VQA) task, for fair comparison with other methods, we extract grid features from ResNet-152 as input image features. The Bottom-up features, i.e., bounding box features, are used to replace the grid features so as to form the best setup for our proposed method in MC VQA.
- In Free-form Opened-ended VQA task (FFOE VQA), at the end of Section 4.2 in our paper: "Following by the current state of the art in FFOE VQA [18], for image representation, we use object detection-based features with FPN detector (ResNet152 backbone)[22], in which the number of maximum detected bounding boxes is set to 50". This means that, in our paper, bounding box features are also used in FFOE for comparison. Mentioned in [18], the bounding box features are the Bottom-up features proposed in [2].
- The grid features extracted by ResNet-152 can also be applied in FFOE VQA. However, at the time that our paper has been written, grid features did not show better performance than bounding box features in FFOE VQA task.

[2] Peter Anderson, Xiaodong He, Chris Buehler, Damien Teney, Mark Johnson, Stephen Gould, and Lei Zhang. Bottom-up and top-down attention for image captioning and VQA. In CVPR, 2018.
[18] ] Jin-Hwa Kim, Jaehyun Jun, and Byoung-Tak Zhang. Bilinear attention networks. In NIPS, 2018.

**Comment by wanng-ide** [comment]
Thank you very much for your patient reply.
